export const projects = [
  {
    id: 1,
    title: "Non Revenue Water",
    location: "Raipur, Chhattisgarh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/a.jpg",
    demoText: "Non Revenue Water Assessment & Reduction Strategy for 24x7 Water Supply Scheme under Raipur Smart City Scheme Funded By World Bank.",
  },
  {
    id: 2,
    title: "Hydraulic Design & Rural Water Supply Scheme",
    location: "Pratappur, Chhattisgarh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/b.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Pratappur Block, Chhattisgarh  for 161 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 3,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Baikunthpur, Chhattisgarh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/c.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Baikunthpur Block, Chhattisgarh  for 228 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 4,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Bemtara, Chhattisgarh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/a.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Bemtara District, Chhattisgarh  for 284 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 5,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Pendri, Chhattisgarh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/b.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Gurela-Pendri-Marwahi District, Chhattisgarh  for 272 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 6,
    title: "Pipeline Rehabilitation & Microtunneling",
    location: "Vasant Kunj, New Delhi",
    industry: "Trenchless",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "17.3 Km Sewer Pipeline & Manhole Rehabilitation with CIPP Technology and Microtunneling.",
  },
  {
    id: 7,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Bijnor, Uttar Pradesh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/a.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Bijnor District, Uttar Pradesh  for 214 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 8,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Gorakhpur, Uttar Pradesh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/b.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Gorakhpur District, Uttar Pradesh  for 346 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 9,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Deoria, Uttar Pradesh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/b.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Deoria District, Uttar Pradesh  for 378 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 10,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Maharajganj, Uttar Pradesh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/b.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Maharajganj District, Uttar Pradesh  for 326 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 11,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Barabanki, Uttar Pradesh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/b.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Barabanki District, Uttar Pradesh  for 179 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 12,
    title: "Rural Water Supply Scheme & Hydraulic Design",
    location: "Lalitpur, Uttar Pradesh",
    industry: "Water",
    capabilities: "Engineering",
    image: "/b.jpg",
    demoText: "Survey, Assessment, Hydraulic Design, Planning, Report including solar system generated pumping technology in Lalitpur District, Uttar Pradesh  for 223 villages including multi & single villages under Jal Jeevan Mission Scheme.",
  },
  {
    id: 13,
    title: "24x7 Water Supply Scheme & GIS Mapping",
    location: "Prayagraj, Uttar Pradesh",
    industry: "Water",
    capabilities: "Smart Solutions",
    image: "/a.jpg",
    demoText: "Geographical Survey, GIS Mapping, Hydraulic Design & Modelling, Assessment & Installation of smart system in Prayagraj Smart City under Smart Cities Scheme. ",
  },
  {
    id: 14,
    title: "24x7 Water Supply Scheme & GIS Mapping",
    location: "Satna, Madhya Pradesh",
    industry: "Water",
    capabilities: "Smart Solutions",
    image: "/a.jpg",
    demoText: "Geographical Survey, GIS Mapping, Hydraulic Design & Modelling, Assessment & Installation of smart system in Satna Smart City under Smart Cities Scheme. ",
  },
  {
    id: 15,
    title: "Pipeline Condition Assessment",
    location: "Vasant Kunj, New Delhi",
    industry: "Infrastructure",
    capabilities: "Trenchless",
    image: "/c.jpg",
    demoText: "17.3 Km Condition Assessment of sewer pipeline for rehabilitation with CCTV & Laser Profiling.",
  },
  {
    id: 16,
    title: "Underground Utility Survey",
    location: "Hauz Khas, New Delhi",
    industry: "Infrastructure",
    capabilities: "Engineering",
    image: "/a.jpg",
    demoText: "13.5 km Underground Utility Survey with GPR Technology for Mictrotunneling works ",
  },
  {
    id: 17,
    title: "Water Pollution Control",
    location: "Bengaluru, Karnataka",
    industry: "Nature Based Solutions",
    capabilities: "Wetland Rejuvenation",
    image: "/b.jpg",
    demoText: "Measurement of Water Flow in Lake from catchment, Water Quality , Geographical Survey & GIS Mapping in entire Bengaluru City for Improvement of Water Pollution & Strengthening of Treatment Facilities to reduction & Control of Water Pollution in Water Bodies under Amrut 2.0 Scheme ",
  },
  {
    id: 18,
    title: "Smart Water Metering",
    location: "Renukoot, Uttar Pradesh",
    industry: "Water",
    capabilities: "Smart Solutions",
    image: "/c.jpg",
    demoText: "Advance Metering Infrastructure with Smart AMR water meters in Aditya Birla Hindalco,Renukoot Residential Quarters",
  },
  {
    id: 19,
    title: "Pipeline Rehabilitation",
    location: "Ahmedabad, Gujarat",
    industry: "Trenchless",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "24 Km Sewer Pipeline & Manhole Rehabilitation with CIPP & MWSL Technology",
  },
  {
    id: 20,
    title: "Water Supply Scheme",
    location: "Minwa, Uttar Pradesh",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Pipeline Laying, Reservoir Construction, Pump House Construction for Minwa,Gorakhpur Water Supply Scheme under Jal Jeevan Mission Scheme. ",
  },
  {
    id: 21,
    title: "Water Supply Scheme",
    location: "Raheemabad, Uttar Pradesh",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Pipeline Laying, Reservoir Construction, Pump House Construction for Raheemabad,Barabanki Water Supply Scheme under Jal Jeevan Mission Scheme. ",
  },
{
    id: 22,
    title: "Water Supply Scheme",
    location: "Daulatganj, Uttar Pradesh",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Pipeline Laying, Reservoir Construction, Pump House Construction for Daulatganj,Barabanki Water Supply Scheme under Jal Jeevan Mission Scheme. ",
  },
{
    id: 23,
    title: "Water Supply Scheme",
    location: "Hariharmahadev, Uttar Pradesh",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Pipeline Laying, Reservoir Construction, Pump House Construction for Hariharmahadev,Lalitpur Water Supply Scheme under Jal Jeevan Mission Scheme. ",
  },
{
    id: 24,
    title: "Water Supply Scheme",
    location: "Jarda, Odisha",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Pipeline Laying, Reservoir Construction, Pump House Construction for Jarda,Rourkela Water Supply Scheme under Jal Jeevan Mission Scheme. ",
  },
{
    id: 25,
    title: "Lake Rejuvenation",
    location: "Jammu, Jammu & Kashmir",
    industry: "Nature Based Solutions",
    capabilities: "Wetland Rejuvenation",
    image: "/c.jpg",
    demoText: "Channi Rama, Jammu Lake Rejuvenation Work including beautification , open gym, green plantation , wetland treatment plant etc.under Amrit Sarovar Scheme. ",
  },
{
    id: 26,
    title: "Lake Rejuvenation",
    location: "Jammu, Jammu & Kashmir",
    industry: "Nature Based Solutions",
    capabilities: "Wetland Rejuvenation",
    image: "/c.jpg",
    demoText: "Channi Himmat, Jammu Lake Rejuvenation Work including beautification , open gym, green plantation , wetland treatment plant etc. under Amrit Sarovar Scheme. ",
  },
{
    id: 27,
    title: "Water Treatment Plant Construction",
    location: "Prova Jagir, Jammu & Kashmir",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Construction of Water Treatment Plant including Raw Water Intake in Prova Jagir, Udhampur Water Supply Scheme under Jal Jeevan Mission ",
  },
{
    id: 28,
    title: "Water Treatment Plant Construction",
    location: "Surni, Jammu & Kashmir",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Construction of Water Treatment Plant including Raw Water Intake in Surni,Ramnagar Water Supply Scheme under Jal Jeevan Mission ",
  },
{
    id: 29,
    title: "Water Treatment Plant Construction",
    location: "Ser Manjla, Jammu & Kashmir",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Construction of Water Treatment Plant including Raw Water Intake in Ser Manjla, Udhampur Water Supply Scheme under Jal Jeevan Mission ",
  },
{
    id: 30,
    title: "Water Treatment Plant Construction",
    location: "Ser Bala, Jammu & Kashmir",
    industry: "Water",
    capabilities: "Construction",
    image: "/c.jpg",
    demoText: "Construction of Water Treatment Plant including Raw Water Intake in Ser Bala, Udhampur Water Supply Scheme under Jal Jeevan Mission ",
  },
{
    id: 30,
    title: "Smart IoT System for 24x7 Water Supply Scheme",
    location: "Bhavnagar, Gujarat",
    industry: "Water",
    capabilities: "Smart Solutions",
    image: "/c.jpg",
    demoText: "24x7 Water Supply Scheme in Bhavnagar with IoT Platform and Establishment of DMA including using Smart SCADA for real time analysis to reduce Non Revenue Water ",
  },
{
    id: 31,
    title: "Smart City Planning",
    location: "Naperville, Illinois",
    industry: "Smart City",
    capabilities: "Engineering",
    image: "/c.jpg",
    demoText: "Survey, Mapping & Preperation of report for the components of Smart Cities Project in the city of Naperville, Illinois ",
  },
{
    id: 32,
    title: "Non Revenue Water & Hydraulic Modelling",
    location: "Dhahran, Saudi Arabia",
    industry: "Water",
    capabilities: "Engineering",
    image: "/c.jpg",
    demoText: "Non Revenue Water Reduction Strategy , DMA Establishment, Hydraulic Modeling with GIS Map in Ajyal South Dhahran,Saudi Arabia  Project",
  },
];
