export const products = [
    {
      id: 1,
      title: "Fort Knox Mill Modifications Cyanide Mixing System",
      location: "Fairbanks, Alaska",
      industry: "Mining",
      capabilities: "Engineering",
      image: "/a.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 2,
      title: "Yellowstone Airport Plaza",
      location: "Belgrade, Montana",
      industry: "Infrastructure",
      capabilities: "Construction",
      image: "/b.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 3,
      title: "Lockwood Water and Sewer District Water Treatment Plant Upgrade Project",
      location: "Billings, Montana",
      industry: "Water",
      capabilities: "Maintenance",
      image: "/c.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 4,
      title: "Copper Mine Development",
      location: "Juneau, Alaska",
      industry: "Mining",
      capabilities: "Construction",
      image: "/a.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 5,
      title: "Urban Bridge Expansion",
      location: "Seattle, Washington",
      industry: "Infrastructure",
      capabilities: "Engineering",
      image: "/b.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 6,
      title: "Central Water Purification System",
      location: "Helena, Montana",
      industry: "Water",
      capabilities: "Engineering",
      image: "/c.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 7,
      title: "Solar Plant Installation",
      location: "Phoenix, Arizona",
      industry: "Renewable Energy",
      capabilities: "Construction",
      image: "/a.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 8,
      title: "Hydroelectric Dam Maintenance",
      location: "Spokane, Washington",
      industry: "Renewable Energy",
      capabilities: "Maintenance",
      image: "/b.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 9,
      title: "Gold Mine Excavation Project",
      location: "Fairbanks, Alaska",
      industry: "Mining",
      capabilities: "Maintenance",
      image: "/c.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 10,
      title: "Airport Modernization Project",
      location: "Denver, Colorado",
      industry: "Infrastructure",
      capabilities: "Engineering",
      image: "/a.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 11,
      title: "Advanced Water Recycling Facility",
      location: "Portland, Oregon",
      industry: "Water",
      capabilities: "Engineering",
      image: "/b.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 12,
      title: "Highway Resurfacing and Expansion",
      location: "Bozeman, Montana",
      industry: "Infrastructure",
      capabilities: "Maintenance",
      image: "/c.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 13,
      title: "Large-Scale Wind Farm Construction",
      location: "Casper, Wyoming",
      industry: "Renewable Energy",
      capabilities: "Construction",
      image: "/a.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 14,
      title: "Pipeline Rehabilitation Project",
      location: "Billings, Montana",
      industry: "Water",
      capabilities: "Maintenance",
      image: "/b.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 15,
      title: "Urban Tunnel Development",
      location: "Seattle, Washington",
      industry: "Infrastructure",
      capabilities: "Construction",
      image: "/c.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 16,
      title: "Wastewater Management System",
      location: "Juneau, Alaska",
      industry: "Water",
      capabilities: "Engineering",
      image: "/a.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 17,
      title: "Geothermal Power Station Setup",
      location: "Reno, Nevada",
      industry: "Renewable Energy",
      capabilities: "Engineering",
      image: "/b.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 18,
      title: "Rural Bridge Repair",
      location: "Boise, Idaho",
      industry: "Infrastructure",
      capabilities: "Maintenance",
      image: "/c.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 19,
      title: "Solar Panel Factory Construction",
      location: "Salt Lake City, Utah",
      industry: "Renewable Energy",
      capabilities: "Construction",
      image: "/a.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
    {
      id: 20,
      title: "Coastal Flood Barrier Installation",
      location: "Portland, Oregon",
      industry: "Water",
      capabilities: "Construction",
      image: "/b.jpg",
      demoText: "Cyanide mixing solutions for Fort Knox Mill improvements.",
    },
];
